### PR TITLE
Add install functionality for 'linux'

### PR DESCRIPTION
**Pull request by 22459**

### CODE REVIEW

**Comment by 22459** [comment]
Hm...I think this should be tested on nonlinux platforms to see what actually happens now that `set(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR})` is removed.

**Comment by alkama** [comment]
Excellent, now at least it wont touch macos \o/
and if it breaks someone's linux machine, it's all on you :)

**Comment by 22459** [comment]
:P

**Comment by Gargaj** [comment]
I'd like someone with an actual Linux system to buddy this.
@plabatut ? @rgiot ?

**Comment by PoroCYon** [comment]
Works for me (Parabola, an Arch derivative).

Though, it'd be cleaner if `CMAKE_SYSTEM_NAME MATCHES "Linux|.*BSD"` was used instead.

**Comment by rgiot** [comment]
On my side, I'm able to compile and install Bonzomatic.
However, I have a segfault at launch

```
OpenSetupDialog STUB
[GLFW] Using GLEW 1.13.0
[GLFW] Obtained framebuffer size: 3840 x 2160
MIDI::Open() failed, continuing anyway...
No valid last shader found, falling back to default...
Bonzomatic: /tmp/Bonzomatic/src/main.cpp:297: int main(int, char**): Assertion `editorOptions.sFontPath.size() > 0' failed.
zsh: abort (core dumped)  /usr/local/bin/Bonzomatic
```


BUT, it does not come from this patch; I have the same problem with the master branch. I have not windows font installed on my current Linux machine (if I remember well it fails to install on ubuntu 17.10) and Bonzomatic cannot work without them

**Comment by 22459** [comment]
Yeah everyone's been getting that, I think some patches got merged to help with that yesterday.

**Pull request merged**
