### PR TITLE
Add support for reading fonts.conf on Linux using tinyxml2

### PR DESCRIPTION
**Pull request by tehe**
Hi,

I tried compiling and running Bonzomatic on Fedora 30 and it couldn't find the default font, so I'm proposing this code change that reads the dirs from /etc/fonts/fonts.conf and scan them and their subdirs for a set of font names, returning the first match.

Regards,
Tomas

### CODE REVIEW

**Comment by Gargaj** [comment]
@PoroCYon

**Comment by Gargaj** [comment]
Also @tehe you might need to update the Travis config to make sure the CI works.

**Comment by PoroCYon** [comment]
This is absolutely not the way to detect the default system font. Please use the `fontconfig` library instead.

**Comment by tehe** [comment]
Fair enough. Let me try then ...

**Pull request closed without merging**
