### PR TITLE
External editor

### PR DESCRIPTION
**Pull request by KoRMaK**
Add the ability to press alt+r to load the shader file from disk. Useful for when you want to edit in an external editor.

### CODE REVIEW

**Comment by Gargaj** [comment]
Is this really necessary? If you have an external editor, why do you even have Bonzo? The internal editor is the whole point.

**Comment by KoRMaK** [comment]
In my situation, I'm learning shaders and so the built in editor is a little much right now while I get acclimated. I'm using an external editor that I'm more familiar with instead and bonzo allows me to quickly pull in those changes, recompile and see the results. So basically, bonzo is acting as a realtime interface for me while I iterate and learn.

In a compo setting, it probably wouldn't be relevant. It might even break the spirit of the compo, I'm not sure. But I figured since it's something I found useful, that others may find useful as well.

**Comment by Gargaj** [comment]
Bonzo's main purpose is always going to be the compo setting; if people want to create a fork that is more suitable tool for home learning, I'm all for it, but my "job" is to make sure that come party time there's a version of the tool that I can say to the best of my knowledge is solid :)

**Comment by KoRMaK** [comment]
Okay, thanks for the clarification.

I'm going to add some more stuff like a previous frame buffer and maybe more, so all those changes can live on over at my place.

Closing this PR then.

**Pull request closed without merging**
