### PR TITLE
Better Misc::GetDefaultFontPath() implementation for OSX (fixes #117)

### LINKED ISSUE #117: Not working on macOS 10.15 beta
On macOS 10.15 beta 1, bonzomatic opens, the resolution selection window is all fine, but when hitting 'ignition' it goes fullscreen then simply exits. No crash report, so it looks like the app is quitting gracefully. Have tested on both GPUs (I have 1 for each screen), also with windowed mode (the app just quits instantly in this case). 

This might be fixed in macOS by release time, but I figured it'd be good to flag it early.

### PR DESCRIPTION
**Pull request by hamidnazari**
[Reportedly](https://www.macworld.com/article/3528553/font-chaos-in-macos-catalina-and-how-to-deal-with-it.html), with the release of Catalina font locations changed. I'm not a Cocoa/Objective C dev, but I've put something together that's hopefully a more reliable way of finding a default font for Bonzomatic on OSX.

I've read that maintainers here are running older versions of OSX, so it would be great if you could verify backwards compatibility with this change.

### CODE REVIEW

**Comment by Gargaj** [comment]
@alkama all yours

**Comment by alkama** [comment]
I did not compile it and test on other mac versions, but code looks smooth.
Although, it seems to be tons of code to find a ttf file.

Since it's the default one (for the rare ppl that dont have a config (that is included in the releases)... aren't we are supposed to know the name and location of that fallback file?

**Comment by alkama** [comment]
In the event that `Courier New.ttf` is not to be found in `/Library/Fonts` anymore on Catalina, we could just add another location there. Since it checks file exist, it should work just fine, or am I overlooking some new kind of macOS Catalina problem?

**Comment by hamidnazari** [comment]
Hi @alkama, I see your point. I suppose we could just add the new font location to the array. I'll send a PR that does that.

**Pull request closed without merging**
