### PR TITLE
Add simple ALSA MIDI support on "X11" platforms like Linux

### PR DESCRIPTION
**Pull request by w23**
Add proper ALSA rawmidi support to `platform_x11/MIDI.cpp`. Move dummy MIDI stub to `platform_common/MIDIDummy.cpp` and reference that on macOS.

ALSA rawmidi will by default enumerate and open all available MIDI devices at startup, but no more than 8 devices (configured with `MAX_MIDI_DEVICES` macro at compile time).
If a device fails (e.g. disconnected), it will be disabled permanently until restart.
It will not monitor new devices availability during Bonzomatic lifetime, including device reconnection.

To open a specific device instead of all available use `MIDI_DEV` environment variable, e.g.: `MIDI_DEV=hw:3,0,0 ./bonzomatic`.

Use `MIDI_VERBOSE` environment variable to print all read midi control change (cc) messages.

### CODE REVIEW

**Comment by Gargaj** [comment]
@PoroCYon

**Comment by PoroCYon** [comment]
Seems to work nicely. One thing though: maybe change the `float fMidiKnob;` to a `uniform float` in the default shader, because the former causes everything to look really glitchy on my machine.

**Comment by PoroCYon** [comment]
Maybe another suggestion: put something for the midi device selection in `config.json` as well. Having some config options in there and others in the environment variables would only lead to a mess.

**Comment by w23** [comment]
@PoroCYon these are great suggestions! It is indeed not very comfortable to work with midi as it is implemented right now. Maybe we should do this for all platforms.

**Pull request merged**
