### PR TITLE
NDI: Update to NDISDK 3

### PR DESCRIPTION
**Pull request by kebby**
Just some maintenance before Revision :) Also changed the pixel format to BGRX for some minor bitrate savings.

### CODE REVIEW

**Comment by Gargaj** [comment]
Nice; wouldn't be a good idea to provide a default fallback if NDI_SDK_DIR is not set though?

**Comment by Gargaj** [comment]
image
*eyetwitch*

**Comment by kebby** [comment]
All changed. A missing NDI sdk throws an error tho instead of just assuming a directory.

**Comment by Gargaj** [comment]
That's fine by me; the assumption is that if someone wants an NDI-compatible build, they should know how to set it up.

**Comment by Gargaj** [comment]
Oddly I'm getting this now:
```
6>c:\program files\newtek\newtek ndi sdk\include\Processing.NDI.structs.h(130): error C2065: 'NULL' : undeclared identifier
6>c:\program files\newtek\newtek ndi sdk\include\Processing.NDI.structs.h(130): error C2065: 'NULL' : undeclared identifier
6>c:\program files\newtek\newtek ndi sdk\include\Processing.NDI.structs.h(174): error C2065: 'NULL' : undeclared identifier
6>c:\program files\newtek\newtek ndi sdk\include\Processing.NDI.structs.h(174): error C2065: 'NULL' : undeclared identifier
```

**Comment by Gargaj** [comment]
Fixed in bbe89d3bf5d1a49034b63aa9637202848ab4ad91

**Comment by kebby** [comment]
Weird. Worked for me (TM) :)

**Comment by Gargaj** [comment]
Could be a compiler version difference? I'm using 2010.

**Comment by kebby** [comment]
2017 here. Must be it.

**Pull request merged**
