### PR TITLE
Use fontconfig on Linux to find appropriate default font.

### PR DESCRIPTION
**Pull request by tehe**
Another stab at improving the code that looks for default font on Linux.

### CODE REVIEW

**Comment by PoroCYon** [comment]
Looks good, but it would be nice if the `font` option in the config file could also work with fontconfig, instead of having to manually specify the entire path. ([relevant code](https://github.com/tehe/Bonzomatic/blob/fc/src/main.cpp#L180-L194)) This isn't a dealbreaker for me, though.

@Gargaj would this functionality (i.e. only specify the font name in the config file) be ok to add?

**Comment by Gargaj** [comment]
"Font name" meaning the filename (stub) or the actual human-readable name?

**Comment by PoroCYon** [comment]
Latter, like the ones [here](https://github.com/tehe/Bonzomatic/blob/fc/src/platform_x11/Misc.cpp#L54-L58).

**Comment by Gargaj** [comment]
I mean I guess? It wouldn't work on Windows / Mac, so it'd break cross-platform compatibility... but I'm not sure if that matters.

**Comment by tehe** [comment]
Thanks for the review and accepting my patch.

**Comment by PoroCYon** [comment]
> I mean I guess? It wouldn't work on Windows / Mac, so it'd break cross-platform compatibility... but I'm not sure if that matters.

Well the paths in the configfile will always be platform-dependent, so, ¯\_(ツ)_/¯

**Comment by Gargaj** [comment]
Not if they're relative to the executable.

**Pull request merged**
