### PR TITLE
Remove dependency to bass, use mini_al+kissFFT instead

### PR DESCRIPTION
**Pull request by Gargaj**
Pls review; (osx) @alkama @sacredbanana (linux) @PoroCYon @rgiot

### CODE REVIEW

**Comment by sacredbanana** [comment]
Oh nice. I'll have a look and test in a few minutes. What is the reason for moving away from Bass?

**Comment by alkama** [comment]
Compiles and works on 10.13, with differences in the FFT. Way stronger bands all over the place. Might still work.

**Comment by linkmauve** [comment]
Note that this also fixes #43, by removing a non-free dependency.

**Comment by rgiot** [comment]
Also compiles  and runs on ubuntu 18.04

**Pull request merged**
